# Copy API keys from 圖庫下載說明/.preview/stock-api.env to tour project .env
param(
    [string]$ProjectRoot = ""
)

if (-not $ProjectRoot) {
    $ProjectRoot = (Get-Location).Path
}

$root = (Resolve-Path $ProjectRoot).Path
$dest = Join-Path $root ".env"
$parent = Split-Path $root -Parent
$stockPickerRoot = Split-Path $PSScriptRoot -Parent

function Read-EnvValue([string]$file, [string]$key) {
    if (-not (Test-Path $file)) { return "" }
    foreach ($line in Get-Content $file -Encoding UTF8) {
        if ($line -match "^\s*$key\s*=\s*(.*)\s*$") {
            return $matches[1].Trim().Trim('"').Trim("'")
        }
    }
    return ""
}

function Find-LegacyEnvFile([string]$fileName, [string]$folderMatch) {
    return Get-ChildItem $parent -Recurse -Filter $fileName -ErrorAction SilentlyContinue |
        Where-Object { $_.FullName -match $folderMatch } |
        Select-Object -First 1
}

function Read-Key([string]$key, [string[]]$files) {
    foreach ($file in $files) {
        if (-not $file -or -not (Test-Path $file)) { continue }
        $value = Read-EnvValue $file $key
        if ($value) { return $value }
    }
    return ""
}

$stockApi = Join-Path $stockPickerRoot ".preview/stock-api.env"
$legacyFree = Join-Path $stockPickerRoot ".preview/free-stock.env"
$legacySstk = Join-Path $stockPickerRoot ".preview/shutterstock.env"

if (-not (Test-Path $stockApi)) {
    $caiFree = Find-LegacyEnvFile "free-stock.env" "CAI12A"
    $caiSstk = Find-LegacyEnvFile "shutterstock.env" "CAI12A"
    if ($caiFree) { $legacyFree = $caiFree.FullName }
    if ($caiSstk) { $legacySstk = $caiSstk.FullName }
}

$keyFiles = @($stockApi, $legacyFree, $legacySstk) | Where-Object { $_ -and (Test-Path $_) }
$lineEnv = Join-Path $parent "LINE\.env"

$pexels = Read-Key "PEXELS_API_KEY" $keyFiles
$unsplashFiles = @($lineEnv) + @($keyFiles)
$unsplash = Read-Key "UNSPLASH_ACCESS_KEY" $unsplashFiles
$pixabay = Read-Key "PIXABAY_API_KEY" $keyFiles
$sstkKey = Read-Key "SHUTTERSTOCK_CONSUMER_KEY" $keyFiles
$sstkSecret = Read-Key "SHUTTERSTOCK_CONSUMER_SECRET" $keyFiles
$sstkToken = Read-Key "SHUTTERSTOCK_API_TOKEN" $keyFiles
$sstkSub = Read-Key "SHUTTERSTOCK_SUBSCRIPTION_ID" $keyFiles

$lines = @(
    "# Auto-generated by tcawg-stock-picker/scripts/setup-env.ps1 - do not commit",
    "PEXELS_API_KEY=$pexels",
    "UNSPLASH_ACCESS_KEY=$unsplash",
    "PIXABAY_API_KEY=$pixabay",
    "SHUTTERSTOCK_CONSUMER_KEY=$sstkKey",
    "SHUTTERSTOCK_CONSUMER_SECRET=$sstkSecret",
    "SHUTTERSTOCK_API_TOKEN=$sstkToken",
    "SHUTTERSTOCK_SUBSCRIPTION_ID=$sstkSub"
)

Set-Content -Path $dest -Value ($lines -join "`n") -Encoding UTF8 -NoNewline
Add-Content -Path $dest -Value "" -Encoding UTF8

Write-Output ".env written to $dest"
Write-Output "Key source: $(if (Test-Path $stockApi) { $stockApi } elseif ($keyFiles.Count -gt 0) { $keyFiles[0] } else { 'MISSING - create .preview/stock-api.env' })"
Write-Output "PEXELS_API_KEY: $(if ($pexels) { 'SET' } else { 'MISSING' })"
Write-Output "UNSPLASH_ACCESS_KEY: $(if ($unsplash) { 'SET' } else { 'MISSING' })"
Write-Output "PIXABAY_API_KEY: $(if ($pixabay) { 'SET' } else { 'MISSING' })"
Write-Output "SHUTTERSTOCK search: $(if ($sstkToken -or ($sstkKey -and $sstkSecret)) { 'SET' } else { 'MISSING' })"
Write-Output "SHUTTERSTOCK license: $(if ($sstkToken -and $sstkSub) { 'SET' } else { 'MISSING (need token + subscription id)' })"
